Feat/bd 16 sign up
itBanda/inctagram pull request #16
Opened 2024-09-24 10:20 UTC by legkovaAnastasia

2024-09-25 07:52 UTC, sfgardev requested changes

2024-09-25 07:52 UTC, sfgardev commented on .env
> +NEXT_PUBLIC_API_URL=https://bandagram.space/api/v1/
add to git ignore

2024-09-25 07:52 UTC, sfgardev commented on pages/sign-up/index.tsx
> +        <form onSubmit={handleSubmit(onSubmit)}>
add form to component

2024-09-25 07:52 UTC, sfgardev commented on package.json
> +    "ui-kit": "file:../ui-kit"
delete ui kit

2024-09-25 07:52 UTC, sfgardev commented on tailwind.config.js
> +// const { palette } = require('uikit-inctagram')
delete comment

2024-09-27 12:42 UTC, legkovaAnastasia commented on tailwind.config.js
> +// const { palette } = require('uikit-inctagram')
done

2024-09-27 12:42 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +        <form onSubmit={handleSubmit(onSubmit)}>
done

2024-09-27 16:31 UTC, sfgardev requested changes

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +    message: 'Passwords must match',
<img width="822" alt="image" src="https://github.com/user-attachments/assets/d8ede266-3d84-436c-8eb1-f48c1b7f77fe">

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +  const [signUp, isLoading] = authApi.useSignUpMutation()
second element of array is object, you can destructure isLoading from it

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +  const [body, setBody] = useState('')
why do we need state here?

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +            <Typography.LinkSm href='/terms-of-service'> Terms of Service</Typography.LinkSm> and{' '}
it should be link from next js

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +            <Typography.LinkSm className='text-accent-500 underline' href='/privacy-policy'>
it should be link from next js

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +        <label className='flex items-center'>
do not add block elements such as div, p and so on inside inline elements such as label

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +      {isModalOpen && (
you can avoid conditional rendering by passing isModalOpen to isOpen prop (isOpened={isModalOpen})

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
remove text-light-900, input already has styles

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
remove text-light-900, input already has styles

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
remove text-light-900, input already has styles

2024-09-27 16:31 UTC, sfgardev commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
remove text-light-900, input already has styles

2024-09-29 16:51 UTC, legkovaAnastasia commented on package.json
> +    "next": "14.2.13",
once i did next dev the system said to update next. we cant use this version?

2024-09-29 16:51 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +    <div className='flex min-h-screen flex-col items-center justify-center bg-dark-900'>
done

2024-09-29 16:51 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +      <Card className='max-w-[378px] text-light-900'>
my mistake

2024-09-29 16:51 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +        <Typography.H1 className='mb-4 text-center text-light-100'>Sign Up</Typography.H1>
done

2024-09-29 16:51 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          label='PasswordConfirmation'
done

2024-09-29 16:51 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +    message: 'Passwords must match',
what for? whats the point of these "eyes" marks if i cant see my password, because if they match its already okey? and i didnt find such request in tasks

2024-09-29 16:51 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +  const [signUp, isLoading] = authApi.useSignUpMutation()
done

2024-09-29 16:51 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +  const [body, setBody] = useState('')
so we can keep state of opened/closed modal and the text of our body(using email from form)

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +            <Typography.LinkSm href='/terms-of-service'> Terms of Service</Typography.LinkSm> and{' '}
and then why we have links in our ui-kit?

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +        <label className='flex items-center'>
done

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +      {isModalOpen && (
done

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
done

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
done

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
done

2024-09-29 16:52 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          className='text-light-900'
done

2024-09-29 17:16 UTC, legkovaAnastasia commented on .env
> +NEXT_PUBLIC_API_URL=https://bandagram.space/api/v1/
done

2024-09-30 08:31 UTC, sfgardev commented on package.json
> +    "next": "14.2.13",
can you please return old version?

2024-09-30 09:05 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +    message: 'Passwords must match',
done

2024-09-30 10:08 UTC, sfgardev requested changes

2024-09-30 14:06 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +          <Button variant='text'>
done

2024-09-30 14:06 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +    // <section className='flex min-h-screen flex-col items-center justify-center bg-dark-900'>
done

2024-09-30 14:06 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +        <div className='mb-4 flex justify-center gap-8 space-x-4'>
done

2024-09-30 14:07 UTC, legkovaAnastasia commented on pages/sign-up/index.tsx
> +      <Card className='max-w-[378px]'>
done

2024-10-01 05:33 UTC, sfgardev approved these changes

2024-10-01 05:35 UTC, merged