BD-18 feat: add forgot password and logic
itBanda/inctagram pull request #25
Opened 2024-10-02 10:00 UTC by pRomKol

2024-10-03 09:56 UTC, sfgardev requested changes

2024-10-03 09:56 UTC, sfgardev commented on components/sign-in-form/SignInForm.tsx
> +
where did u get this imports, looks like old commit

2024-10-03 09:56 UTC, sfgardev commented on components/sign-in-form/SignInForm.tsx
> +  const [login, { error, isError, isLoading }] = authApi.useLoginMutation()
looks like old commit

2024-10-03 09:56 UTC, sfgardev commented on components/sign-in-form/SignInForm.tsx
> +      router.push('/profile')
old commit

2024-10-03 09:56 UTC, sfgardev commented on package.json
> +    "@types/react-google-recaptcha": "^2.1.9",
should be in dev dependencies and version should be fixed by deleting ^

2024-10-03 09:56 UTC, sfgardev commented on package.json
> +    "react-google-recaptcha": "^3.1.0",
version should be fixed

2024-10-03 09:56 UTC, sfgardev commented on services/auth/authSlice.ts
> +    passwordRecovery: builder.mutation<PasswordRecoveryRequest, void>({
first argument of generic should be response

2024-10-03 10:04 UTC, pRomKol commented on components/forgot-password-form/ForgotPasswordForm.tsx
> +      // if (isFetchBaseQueryError(err)) {
done

2024-10-03 10:04 UTC, pRomKol commented on components/sign-in-form/SignInForm.tsx
> +
done

2024-10-03 10:10 UTC, pRomKol commented on components/sign-in-form/SignInForm.tsx
> +  const [login, { error, isError, isLoading }] = authApi.useLoginMutation()
done

2024-10-03 10:11 UTC, pRomKol commented on components/sign-in-form/SignInForm.tsx
> +      router.push('/profile')
done

2024-10-03 10:11 UTC, pRomKol commented on package.json
> +    "@types/react-google-recaptcha": "^2.1.9",
done

2024-10-03 10:11 UTC, pRomKol commented on package.json
> +    "react-google-recaptcha": "^3.1.0",
done

2024-10-03 10:11 UTC, pRomKol commented on services/auth/authSlice.ts
> +    passwordRecovery: builder.mutation<PasswordRecoveryRequest, void>({
done

2024-10-04 05:29 UTC, sfgardev approved these changes

2024-10-04 05:29 UTC, merged