Fix/bd 42 remove autocomlete
itBanda/inctagram pull request #26
Opened 2024-10-02 12:07 UTC by legkovaAnastasia

my decision may be not most elegant, but chrome dont react to autoComplite='none' (or 'off', 'false'), so there are 2 display none inputs. and sorry for bad commit naming, tried to rename it

2024-10-02 14:05 UTC, SlavaMryasov requested changes
please check code after complete

2024-10-02 14:05 UTC, SlavaMryasov commented on components/sign-up-form/SignUpForm.tsx
> +          <input className='hidden' name='username' readOnly='true' type='text' />
do not need readOnly

2024-10-02 14:11 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +            autocomlete='none'
done

2024-10-02 14:19 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +      <form autoComplete='off' onSubmit={handleSubmit(onSubmit)}>
maybe its unnecessary, but was recomended in discussions, when i was checking out the problem of outocomplete attr. i delete it now, hope it will work right way in different versions of chrome

2024-10-02 14:21 UTC, legkovaAnastasia commented on components/sign-up-form/SignUpForm.tsx
> +          <input className='hidden' name='username' readOnly='true' type='text' />
ok

2024-10-03 10:35 UTC, SlavaMryasov requested changes

2024-10-03 10:35 UTC, SlavaMryasov commented on components/sign-up-form/SignUpForm.tsx
> +          <input name='username' readOnly='true' style={{ display: 'none' }} type='text' />
if you use truthful value you should not write argument value (write "readOnly" instead of "readOnly='true'")

2024-10-03 10:35 UTC, SlavaMryasov commented on components/sign-up-form/SignUpForm.tsx
> +            autoComplete='none'
if you remove autoComplete='none' nothing will change (in all inputs)

2024-10-04 07:47 UTC, SlavaMryasov approved these changes

2024-10-04 08:33 UTC, sfgardev approved these changes

2024-10-04 08:34 UTC, merged