Bd-30 feat: internationalization
itBanda/inctagram pull request #37
Opened 2024-10-04 11:45 UTC by KateTernovskaya

2024-10-07 10:29 UTC, sfgardev requested changes

2024-10-07 10:51 UTC, KateTernovskaya commented on assets/lang-img/FlagEn.svg
convert svg to png

2024-10-07 10:51 UTC, KateTernovskaya commented on hocs/useTranslation.tsx
done

2024-10-07 12:05 UTC, sfgardev commented on public/locales/en.ts
you can re-export en.ts from public

2024-10-07 12:05 UTC, sfgardev commented on public/locales/ru.ts
you can re-export ru.ts from public

2024-10-09 10:14 UTC, sfgardev approved these changes

2024-10-09 10:17 UTC, merged