BD-52 feat: add sidebar
itBanda/inctagram pull request #38
Opened 2024-10-17 10:04 UTC by pRomKol

2024-10-22 05:54 UTC, sfgardev requested changes

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
rename file to Navbar

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
> +type Props = ComponentProps<'aside'>
why do we need props here?

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
> +    startTransition(() => {
for what purpose you use startTransition?

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
> +  ]
it would be better to move these menus to separate file

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
> +    <SideBar className={className}>
add styles here, instead of passing className

2024-10-22 05:54 UTC, sfgardev commented on components/navbar/NavBar.tsx
> +      <ConfirmationModal
you can move ConfirmationModal out of Sidebar by wrapping all by fragment

2024-10-22 05:54 UTC, sfgardev commented on public/locales/en.ts
> +    button: {
if you add logout to button, remove it from here

2024-10-22 05:55 UTC, sfgardev commented
<img width="767" alt="image" src="https://github.com/user-attachments/assets/5eb0e98a-3813-4bd8-9d2a-c3623f7abf08">

2024-10-24 13:38 UTC, sfgardev requested changes

2024-10-24 13:38 UTC, sfgardev commented on components/navbar/Navbar.tsx
> +export type MenuItem = {
move to constants

2024-10-24 13:38 UTC, sfgardev commented on components/navbar/Navbar.tsx
> +            className='mt-auto flex items-center gap-3 p-0 font-medium text-light-100' // Добавьте временный фон для отладки
remove comment

2024-10-24 13:38 UTC, sfgardev commented on components/navbar/Navbar.tsx
> +      <li className='text-light-100' key={menuItem.label}>
fix ts errors

2024-10-25 09:17 UTC, sfgardev requested changes

2024-10-25 09:17 UTC, sfgardev commented on components/navbar/constans.tsx
change name to constants

2024-10-25 09:17 UTC, sfgardev commented on components/navbar/Navbar.tsx
> +  const [activeLink, setActiveLink] = useState(router.pathname)
useState is redundant here, instead use usePathname hook
https://medium.com/@theambi/how-to-easily-style-active-link-in-nextjs-ebd01a484f23 see example here

2024-10-25 09:17 UTC, sfgardev commented on components/navbar/Navbar.tsx
> +          className={`flex items-center gap-3 transition ${activeLink === menuItem.href ? 'text-accent-100' : 'hover:text-accent-100 active:text-accent-700'}`}
use cn for dynamic styles

2024-10-25 10:19 UTC, pRomKol commented on components/navbar/Navbar.tsx
> +  const [activeLink, setActiveLink] = useState(router.pathname)
done

2024-10-25 10:19 UTC, pRomKol commented on components/navbar/Navbar.tsx
> +          className={`flex items-center gap-3 transition ${activeLink === menuItem.href ? 'text-accent-100' : 'hover:text-accent-100 active:text-accent-700'}`}
done

2024-10-25 11:20 UTC, pRomKol commented on components/navbar/constans.tsx
done

2024-10-25 15:00 UTC, sfgardev approved these changes

2024-10-25 15:00 UTC, merged