BD-55 feat: upload photo
itBanda/inctagram pull request #39
Opened 2024-10-19 19:40 UTC by SlavaMryasov

2024-10-20 09:01 UTC, sfgardev requested changes

2024-10-20 09:01 UTC, sfgardev commented on services/profile/index.ts
> +export type { AvatarResponse, ProfileResponse } from './types'
no need to re-export if do not use it outside slice

2024-10-20 09:27 UTC, SlavaMryasov commented on components/profile-photo/ProfilePhoto.tsx
> +    <div className='m-6 box-border w-[196px]'>
so that it would be beautiful during development, deleted

2024-10-20 09:37 UTC, SlavaMryasov commented on components/modals/ProfilePhotoModal.tsx
> +      className='h-[536px] max-w-[492px] overflow-hidden'
why hidden? I don't know - fixed
height fixed

2024-10-20 09:50 UTC, SlavaMryasov commented on components/profile-photo/modes/ChoosePhotoMode.tsx
> +      {photoError && <Alert isOpened message={photoError} type='error' />}
I centered the text, but didn't put the word "Error" in bold because it looks dirty in code

2024-10-20 09:52 UTC, SlavaMryasov commented on components/profile-photo/modes/ChoosePhotoMode.tsx
> +      <Card className='mt-6 flex h-[228px] w-[222px] items-center justify-center'>
replaced with div

2024-10-20 09:53 UTC, SlavaMryasov commented on package.json
> +    "react-easy-crop": "^5.0.8",
done

2024-10-20 09:55 UTC, SlavaMryasov commented on services/profile/types.ts
> +  }[]
replaced with AvatarResponse

2024-10-20 13:22 UTC, SlavaMryasov commented on components/ui/spinner/Spinner.tsx
> +    <div className={`fixed ${modal ? '' : 'inset-0'} bg-dark-700 backdrop-blur-sm ${className}`}>
added cn

2024-10-20 13:48 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +type CroppedArea = { height: number; width: number; x: number; y: number }
done

2024-10-20 14:05 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +  const { refetch } = profileApi.useProfileQuery()
const { refetch: refetchProfile } = profileApi.useProfileQuery() 
  this is the only way to do it

2024-10-20 14:15 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +  const [loadAvatar, { isLoading }] = profileApi.useLoadAvatarMutation()
done

2024-10-20 14:32 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    formData.append('file', croppedImg as Blob)
if I don't use an assertion, I will need to do checks, and I'm sure there will be a blob

2024-10-20 14:36 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    setZoom(Math.min(Math.max(newZoom, 1), 3))
0.001 - for smooth zoom
1 - min zoom
3 - max zoom

2024-10-21 04:23 UTC, sfgardev commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    setZoom(Math.min(Math.max(newZoom, 1), 3))
sounds good, but can you add it to constants?

2024-10-21 04:45 UTC, sfgardev commented on components/modals/ProfilePhotoModal.tsx
> +export const ProfilePhotoModal = ({ isOpened, onClose, ...props }: Props) => {
it looks like you do not need to spread props in this case, you already pass isOpened and onClose

2024-10-21 05:01 UTC, sfgardev commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    const croppedImg = await getCroppedImg(imageSrc!, croppedArea!)
maybe use early return pattern?

2024-10-21 05:04 UTC, sfgardev commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    formData.append('file', croppedImg as Blob)
you should add type to return value of getCroppedImg, it not only can be blob it also can be null

2024-10-21 07:13 UTC, sfgardev requested changes

2024-10-21 07:13 UTC, sfgardev commented on components/profile-photo/ProfilePhoto.tsx
> +import { Spinner } from '../ui'
change imports

2024-10-21 09:26 UTC, sfgardev requested changes

2024-10-21 09:26 UTC, sfgardev commented on components/modals/ProfilePhotoModal.tsx
add re-export to modals/index.ts

2024-10-21 09:26 UTC, sfgardev commented on components/profile-photo/ProfilePhoto.tsx
add re-export to componets/index.ts

2024-10-21 09:26 UTC, sfgardev commented on components/profile-photo/ProfilePhoto.tsx
> +  const [deleteAvatar, { isLoading: isLoadingDelete }] = profileApi.useDeleteAvatarMutation()
isLoadingDelete what? isLoadingDeleteAvatar is more clearly

2024-10-21 09:26 UTC, sfgardev commented on components/profile-photo/modes/SendPhotoMode.tsx
> +        className={clsx(
use cn instead clsx

2024-10-21 09:26 UTC, sfgardev commented on package.json
> +    "clsx": "^2.1.1",
fix version

2024-10-21 09:26 UTC, sfgardev commented on package.json
> +    "tailwind-merge": "^2.5.4",
fix version

2024-10-23 12:40 UTC, SlavaMryasov commented on components/modals/ProfilePhotoModal.tsx
> +export const ProfilePhotoModal = ({ isOpened, onClose, ...props }: Props) => {
done

2024-10-23 12:43 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    const croppedImg = await getCroppedImg(imageSrc!, croppedArea!)
done

2024-10-23 14:55 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    formData.append('file', croppedImg as Blob)
done

2024-10-23 14:55 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +    setZoom(Math.min(Math.max(newZoom, 1), 3))
done

2024-10-23 14:56 UTC, SlavaMryasov commented on components/profile-photo/ProfilePhoto.tsx
> +import { Spinner } from '../ui'
done

2024-10-23 14:59 UTC, SlavaMryasov commented on components/profile-photo/ProfilePhoto.tsx
> +          <Icon
done

2024-10-23 15:00 UTC, SlavaMryasov commented on components/modals/ProfilePhotoModal.tsx
done

2024-10-23 15:01 UTC, SlavaMryasov commented on components/profile-photo/ProfilePhoto.tsx
done

2024-10-23 15:02 UTC, SlavaMryasov commented on components/profile-photo/ProfilePhoto.tsx
> +  const [deleteAvatar, { isLoading: isLoadingDelete }] = profileApi.useDeleteAvatarMutation()
done

2024-10-23 15:02 UTC, SlavaMryasov commented on components/profile-photo/modes/SendPhotoMode.tsx
> +        className={clsx(
done

2024-10-23 15:03 UTC, SlavaMryasov commented on package.json
> +    "tailwind-merge": "^2.5.4",
done

2024-10-24 13:49 UTC, sfgardev approved these changes

2024-10-24 13:49 UTC, merged