BD-54 feat: fill-in profile
itBanda/inctagram pull request #41
Opened 2024-10-28 10:43 UTC by legkovaAnastasia

2024-10-31 06:35 UTC, sfgardev requested changes

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
configure your IDE, please! 
<img width="1260" alt="image" src="https://github.com/user-attachments/assets/57fb0442-e58a-4ccc-8d4d-da41bc67ef9b">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +  const dataUsername = data?.userName
no need to declare a variable here

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +      userName: dataUsername,
<img width="679" alt="image" src="https://github.com/user-attachments/assets/40f893f1-d28a-4889-8f35-a3e6431d1ed9">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +  const handleDateChange = date => {
<img width="665" alt="image" src="https://github.com/user-attachments/assets/aebbe3c6-aa17-44a8-873e-a94654f8ee01">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +          errorText={
<img width="692" alt="image" src="https://github.com/user-attachments/assets/e338caea-ce8c-4418-a906-e1d11118cd90">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +                  // onClick={() => sessionStorage.setItem('formData', JSON.stringify(getValues()))}
remove comment

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +            value={countryField}
<img width="651" alt="image" src="https://github.com/user-attachments/assets/9d677a95-4f17-419a-9c24-0941f43d9c19">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +            options={cities?.map(city => ({
<img width="588" alt="image" src="https://github.com/user-attachments/assets/fc2b29ea-28cc-4adb-b52c-ab56e89e87e3">

2024-10-31 06:35 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +            value={cityField.value}
<img width="636" alt="image" src="https://github.com/user-attachments/assets/b60b55d2-f1e3-4aac-8455-0ff8dbfc06e4">

2024-10-31 06:35 UTC, sfgardev commented on components/profile-photo/ProfilePhoto.tsx
> +    <div className='relative w-[196px] pt-6'>
<img width="206" alt="image" src="https://github.com/user-attachments/assets/6e213f90-eae9-4148-8d5f-99661b38da06">
button position

2024-10-31 06:35 UTC, sfgardev commented on package.json
> +    "@types/country-list": "^2.1.4",
fix version

2024-10-31 06:35 UTC, sfgardev commented on public/locales/en.ts
> +    select_your_country: 'Select your country',
use camelCase

2024-10-31 06:35 UTC, sfgardev commented on services/profile/profileSlice.ts
> +    setProfileInfo: builder.mutation<{}, ProfileRequest>({
updateProfileInfo is more clear

2024-10-31 11:29 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
done

2024-10-31 11:30 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +      userName: dataUsername,
done

2024-10-31 11:30 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +  const handleDateChange = date => {
done

2024-10-31 12:08 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +          errorText={
maybe we need to change type of errorText to ReactNode so we can use not only string, otherwise i must render extra element and it doesent correspond to design (watch last commit)

2024-10-31 12:08 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +                  // onClick={() => sessionStorage.setItem('formData', JSON.stringify(getValues()))}
done

2024-10-31 12:08 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +            value={countryField}
done

2024-10-31 12:09 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +            options={cities?.map(city => ({
done

2024-10-31 12:09 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +            value={cityField.value}
done

2024-10-31 12:09 UTC, legkovaAnastasia commented on package.json
> +    "@types/country-list": "^2.1.4",
done

2024-10-31 12:09 UTC, legkovaAnastasia commented on public/locales/en.ts
> +    select_your_country: 'Select your country',
ok

2024-10-31 12:10 UTC, legkovaAnastasia commented on services/profile/profileSlice.ts
> +    setProfileInfo: builder.mutation<{}, ProfileRequest>({
ok

2024-11-03 15:32 UTC, sfgardev requested changes

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +          errorText={
sounds good

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +      <Alert
<img width="900" alt="image" src="https://github.com/user-attachments/assets/1ecd0d75-1020-430e-8baa-0faf66d6aa1b">

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +              errors.dateOfBirth && (
<img width="843" alt="image" src="https://github.com/user-attachments/assets/8e6c8b26-f0b3-4c54-b9d5-68b3ade5313f">

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +                      query: { ...getValues() },
no need to spread, just call getValues

2024-11-03 15:32 UTC, sfgardev commented on package.json
> +    "country-state-city": "3.2.1",
you have same package in devDeps

2024-11-03 15:32 UTC, sfgardev commented on package.json
> +    "country-state-city": "3.2.1",
you have same package country-state-city in deps

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +  const [setProfileInfo, { isLoading }] = profileApi.useUpdateProfileInfoMutation()
updateProfileInfo is more clear naming and you can rename isLoading: isLoadingUpdateProfileInfo

2024-11-03 15:32 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +            onChange: async () => await trigger('aboutMe'),
why do we need onChange here? when i type fast or delete, ui is lagging, without it working ok

2024-11-03 15:53 UTC, sfgardev requested changes

2024-11-03 15:53 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +                    value: city.name + [' '] + city.stateCode,
can we use ' ' instead of [' ']?

2024-11-03 15:53 UTC, sfgardev commented on components/profile/GeneralInformationForm.tsx
> +        ></TextArea>
you can make textarea self closed

2024-11-04 04:54 UTC, legkovaAnastasia commented on services/profile/types.ts
> +export type ProfileRequest = {
ok

2024-11-04 05:05 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +              errors.dateOfBirth && (
done

2024-11-04 05:08 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +                      query: { ...getValues() },
done

2024-11-04 05:16 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +  const [setProfileInfo, { isLoading }] = profileApi.useUpdateProfileInfoMutation()
ok

2024-11-04 05:29 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +                    value: city.name + [' '] + city.stateCode,
ok

2024-11-04 05:29 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +        ></TextArea>
ok

2024-11-04 05:31 UTC, legkovaAnastasia commented on package.json
> +    "country-state-city": "3.2.1",
ok

2024-11-04 05:31 UTC, legkovaAnastasia commented on package.json
> +    "country-state-city": "3.2.1",
done

2024-11-04 05:46 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +            onChange: async () => await trigger('aboutMe'),
deleted onchange

2024-11-04 06:15 UTC, legkovaAnastasia commented on components/profile/GeneralInformationForm.tsx
> +      <Alert
done

2024-11-04 07:48 UTC, sfgardev approved these changes

2024-11-04 07:49 UTC, merged