BD-66 feat: avatar component
itBanda/inctagram pull request #42
Opened 2024-10-28 16:29 UTC by sfgardev

2024-10-28 17:47 UTC, SlavaMryasov requested changes

2024-10-28 17:47 UTC, SlavaMryasov commented on pages/profile/[id].tsx
> +            <Link href='/profile/settings'>{t.profile.button.profileSettings}</Link>
use profileId, your path is hardcode

2024-10-28 17:47 UTC, SlavaMryasov commented on pages/profile/[id].tsx
> +    return <p className='text-light-100'>Profile id is invalid</p>
u should use value from internationalization but no hardcode

2024-10-28 17:47 UTC, SlavaMryasov commented on services/public-user/publicUserSlice.ts
> +        url: `public-user/profile/${profileId}`,
if we wrote "method" in other slices, perhaps we need to write it here too?

2024-10-28 17:47 UTC, SlavaMryasov commented on services/public-user/types.ts
> +export type Avatar = {
this type is already in 'services/profile'

2024-10-29 05:41 UTC, sfgardev commented on pages/profile/[id].tsx
> +            <Link href='/profile/settings'>{t.profile.button.profileSettings}</Link>
for what purpose shouild i use profileId?

2024-10-29 05:43 UTC, sfgardev commented on services/public-user/publicUserSlice.ts
> +        url: `public-user/profile/${profileId}`,
it is like placeholder here, in future we should redirect to 404 page, so no need to translate it

2024-10-29 05:44 UTC, sfgardev commented on pages/profile/[id].tsx
> +    return <p className='text-light-100'>Profile id is invalid</p>
it is like placeholder here, in future we should redirect to 404 page, so no need to translate it

2024-10-29 05:45 UTC, sfgardev commented on services/public-user/publicUserSlice.ts
> +        url: `public-user/profile/${profileId}`,
we need to use method only for mutation, no need to write method in query

2024-10-29 06:12 UTC, sfgardev commented on services/public-user/types.ts
> +export type Avatar = {
done

2024-10-29 07:57 UTC, SlavaMryasov approved these changes

2024-10-29 07:57 UTC, merged