Bd 73 fix: header styles
itBanda/inctagram pull request #46
Opened 2024-11-07 10:29 UTC by KateTernovskaya

2024-11-08 04:53 UTC, sfgardev requested changes

2024-11-08 04:53 UTC, sfgardev commented on components/notification/NotificationBell.tsx
> +  }, [isOpen])
it is not working properly, you can add console.log to your handlers and check

2024-11-08 04:53 UTC, sfgardev commented on components/notification/NotificationBell.tsx
> +          <NotificationModal notifications={exampleNotifications} />
you can add className prop to NotificationModal and get rid off redundant div wrapper

2024-11-08 04:53 UTC, sfgardev commented on components/notification/NotificationBell.tsx
> +        </div>
when i click and hover on countNote it is not working

2024-11-11 09:25 UTC, KateTernovskaya commented on components/notification/NotificationBell.tsx
> +          <NotificationModal notifications={exampleNotifications} />
done

2024-11-11 12:03 UTC, KateTernovskaya commented on components/notification/NotificationBell.tsx
> +        </div>
done

2024-11-14 14:29 UTC, sfgardev requested changes

2024-11-14 14:29 UTC, sfgardev commented on components/notification/NotificationBell.tsx
> +    }
you can move this logic at the top of useEffect, because if is open === false no need to create handlers

2024-11-15 08:18 UTC, KateTernovskaya commented on public/locales/en.ts
> +    backToProfileSettings: "Back to prifile settings",
done

2024-11-15 08:18 UTC, KateTernovskaya commented on components/notification/NotificationBell.tsx
> +    }
done

2024-11-15 08:29 UTC, sfgardev approved these changes

2024-11-15 08:31 UTC, merged